POST http://localhost:8080/events
content-type: application/json

{
    "name": "Garima",
    "description": "Second test event",
    "location": "mumbai",
    "dateTime": "2025-01-02T15:30:00.000Z"
}