POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdXRlbGEyQGdtYWlsLmNvbSIsImV4cCI6MTc3NDQ5NjQ0NSwidXNlcklkIjozfQ.cX8tRqa1D582OptbHpGY6kKIVWzFvhJOMj4yLhq1mwM

{
    "name": "Ritvik",
    "description": "Sixth test event",
    "location": "delhi",
    "dateTime": "2025-01-02T15:30:00.000Z"
}