DELETE http://localhost:8080/event/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdXRlbGExQGdtYWlsLmNvbSIsImV4cCI6MTc3NDUwNTAxMywidXNlcklkIjoyfQ.ipIHoDXuA_Uh5jSdeB22cvj7VSUfPNZIsaTDvUy1qtI