DELETE http://localhost:8080/event/6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdXRlbGFAZ21haWwuY29tIiwiZXhwIjoxNzc0NTA0Nzg5LCJ1c2VySWQiOjF9._91k9k6CxhC3peBD8_lqnxEyQgphpyHmGcZg-C-rZoM