DELETE http://localhost:8080/event/3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdXRlbGEyQGdtYWlsLmNvbSIsImV4cCI6MTc3NDQ5NjQ0NSwidXNlcklkIjozfQ.cX8tRqa1D582OptbHpGY6kKIVWzFvhJOMj4yLhq1mwM